name: continuous-integration-isaac

on:
  pull_request:
    types: [opened, reopened]
  
jobs:
  analizar_codigo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ejecucion de pruebas SAST
        run: echo Realizando análisis de SAST
      - name: Comprobar requisitos
        run: |
          if [ -f allow_pull_request.txt ]; then
            echo "allow_pull=true" >> $GITHUB_ENV
          else
            echo "allow_pull=false" >> $GITHUB_ENV
      - name: Build
        if: ${{ env.allow_pull == 'true'}}
        run: echo Permitiendo pull requests
      - name: Impedir Build
        if: ${{ env.allow_pull == 'false'}}
        run: echo Build fallida && exit 1
